### ISSUE TITLE
Test segfault on armv7hl

### ISSUE THREAD

**Issue by eclipseo** [rust-av/aom-rs#25] opened 2019-12-06 23:05 UTC
On armv7hl only, i686 is good:

```
Running `/builddir/build/BUILD/aom-sys-0.1.3/target/release/deps/aom_sys-e44a63ac9358c24c`
running 32 tests
test aom::bindgen_test_layout_Av1DecodeReturn ... ok
test aom::bindgen_test_layout___fsid_t ... ok
test aom::bindgen_test_layout_aom_active_map ... ok
test aom::bindgen_test_layout_aom_codec_ctx__bindgen_ty_1 ... ok
test aom::bindgen_test_layout_aom_codec_cx_pkt ... ok
test aom::bindgen_test_layout_aom_codec_cx_pkt__bindgen_ty_1 ... ok
test aom::bindgen_test_layout_aom_codec_cx_pkt__bindgen_ty_1__bindgen_ty_1 ... ok
test aom::bindgen_test_layout_aom_codec_cx_pkt__bindgen_ty_1_aom_psnr_pkt ... ok
test aom::bindgen_test_layout_aom_codec_dec_cfg ... ok
test aom::bindgen_test_layout_aom_codec_enc_cfg ... ok
test aom::bindgen_test_layout_aom_codec_frame_buffer ... ok
test aom::bindgen_test_layout_aom_codec_stream_info ... ok
test aom::bindgen_test_layout_aom_fixed_buf ... ok
test aom::bindgen_test_layout_aom_image ... ok
test aom::bindgen_test_layout_aom_image_rect ... ok
test aom::bindgen_test_layout_aom_inspect_init ... ok
test aom::bindgen_test_layout_aom_postproc_cfg ... ok
test aom::bindgen_test_layout_aom_rational ... ok
test aom::bindgen_test_layout_aom_roi_map ... ok
test aom::bindgen_test_layout_aom_scaling_mode ... ok
test aom::bindgen_test_layout_aom_svc_layer_id ... ok
test aom::bindgen_test_layout_aom_svc_params ... ok
test aom::bindgen_test_layout_aom_svc_ref_frame_config ... ok
test aom::bindgen_test_layout_aom_tile_data ... ok
test aom::bindgen_test_layout_av1_ext_ref_frame ... ok
test aom::bindgen_test_layout_av1_ref_frame ... ok
test aom::bindgen_test_layout_cfg_options ... ok
test aom::bindgen_test_layout_imaxdiv_t ... ok
test aom::bindgen_test_layout_max_align_t ... ok
test tests::version ... ok
test aom::bindgen_test_layout_aom_codec_ctx ... ok
error: process didn't exit successfully: `/builddir/build/BUILD/aom-sys-0.1.3/target/release/deps/aom_sys-e44a63ac9358c24c` (signal: 11, SIGSEGV: invalid memory reference)
```

Looks like tests::encode is segfaulting for some reason.

**Comment by lu-zero** [comment] 2019-12-07 05:58
could you please append a debugger and provide a backtrace?

**Comment by lu-zero** [comment] 2020-05-19 17:45
Is still a problem?

**Comment by decathorpe** [comment] 2020-10-20 14:58
Sorry for not getting back to this sooner.
I am unable to reproduce the original issue with aom-sys 0.2.1, so feel free to close this bug.

**Comment by lu-zero** [comment] 2020-10-20 15:37
Good to know :)

**Closed as completed by lu-zero** 2020-10-20 15:37 UTC
Labels: bug, help wanted
